### ISSUE TITLE
More expressive strategies

### ISSUE THREAD

**Issue by eugene-eeo** [datalib/libextract#8]
Currently, the "native" way for expressing strategies are to put them in a tuple/list. However this is not very good as the user will need to list out every function used if he/she wants to add one more step in the middle. A better solution is needed. Perhaps using two objects, ``Decl`` and ``Impl`` we can write a "framework" or syntactic sugar for writing strategies. To implement them:

```python
impl = Impl.from_functions(ARTICLE_NODE)

@impl.replaces('get_etree')
def get_etree(doc):
    return something
```

And then to combine them:

```python
pipe = Decl.from_functions(ARTICLE_NODE)\
           .after('get_etree', do='preprocess')\
           .after('histogram', do='store_data')\
           .plug(impl)
node = pipeline(fileobj, pipe)
```

Although I have yet to find an aesthetically pleasing method. The proposed one seems a bit ugly to me.

cc @rodricios

**Comment by rodricios** [comment]
You're sort of putting into words what I had in mind with the decorators suggestion I made in #1. 

Instead of decorator ``imp.replaces(..)``:
```python
@impl.replaces('get_etree')
def get_etree(doc):
    return something
```

It'd be cool if the user can simply define ``get_tree``; then a preprocessor, instigated by ``libextract.extract(..)`` or some global monitor scans and accesses the default get_tree and swaps it from it's original place in the _BASE strategy. I don't know if/don't think that's possible to do from within the decorated function...

I'm going to ruminate on this some more and get back to you tomorrow (pst where I'm at). gn!
